<template>
  <NucGridPage v-bind:gap="{'col':0,'row':0}" v-bind:rows="[1]"
    v-bind:schema="{'r0-c0':{'col':0,'row':0,'showIn':['xs','sm','md','lg'],'colSpan':1,'rowSpan':1}}"
    v-bind:columns="[1]" overflow="auto" v-bind:designMode="false" v-bind:minNsLimit="1614"
    v-bind:style="{'background':'#FFFFFF','paddingTop':'0px','paddingLeft':'0px','paddingRight':'0px','paddingBottom':'0px'}">
    <NucGridCell v-bind:wrap="true" v-bind:reverse="false" overflow="hidden" direction="column"
      v-bind:showInDevice="['xs','sm','md','lg']" verticalAlignment="top" horizontalAlignment="left"
      id="fa5a03c8-5402-43e9-b301-6ae916686cc5" v-bind:col="0" v-bind:row="0" v-bind:colSpan="1" v-bind:rowSpan="1"
      v-bind:marginTop="0" v-bind:marginLeft="0" v-bind:marginRight="0" v-bind:marginBottom="0"
      v-bind:style="{'height':'auto','background':'transparent','paddingTop':'0px','borderColor':'','borderStyle':'solid','borderWidth':'0px','paddingLeft':'0px','borderRadius':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'1px','borderTopRightRadius':'1px','borderBottomLeftRadius':'1px','borderBottomRightRadius':'1px'}"
      slot="r0-c0" area="r0-c0">
      <NucGroupElement top="0%" left="0%" v-bind:snapX="false" v-bind:snapY="true" bgColor="" position="absolute"
        ncTooltipText="" id="a47d133a-595b-4454-8fad-7189be3c6258"
        v-bind:style="{'color':'#FFFFFF','width':'1047.75px','height':'571.5px','zIndex':2,'fontSize':'11.25px','maxWidth':'','minWidth':'7.5','tabIndex':'-0.75','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'7.5','textAlign':'center','background':'','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.9375','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.75px','textDecoration':'none','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
        <NucGroupElement top="4.730617608409987%" left="0.07132667617689016%" v-bind:snapX="false" v-bind:snapY="false"
          bgColor="" position="absolute" ncTooltipText="" id="d7c76a5c-2529-421c-841c-a2b580262006"
          v-bind:style="{'color':'#FFFFFF','width':'1614.75px','height':'88.5px','zIndex':4,'fontSize':'11.25px','maxWidth':'','minWidth':'7.5','tabIndex':'-0.75','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'7.5','textAlign':'center','background':'#022b56','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.9375','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.75px','textDecoration':'none','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
          <WImage top="27.11864406779661%" left="9.571428571428571%" v-bind:blank="false" v-bind:snapX="false"
            v-bind:snapY="false" v-bind:rounded="false" stretch="none"
            imageUrl="https://simplar.atakansaracoglu.com/wp-content/uploads/elementor/thumbs/simplar-logo-light-pfjjv721dh8fum3hov6zq87i60hbahainwcyeqty1c.png"
            position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
            v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
            ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
            id="387bcc9f-aae0-4a3a-9aca-085cba2208fb"
            v-bind:style="{'width':'','height':'','zIndex':6,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
          <TwSimpleDropdown top="32.20338983050848%" left="28.357142857142858%" v-bind:snapX="false"
            v-bind:snapY="false" v-bind:options="[]" itemHref="#" position="absolute" v-bind:selected="[]" dataModel=""
            itemWidth="tw-w-36" itemRadius="tw-rounded-md" itemShadow="tw-shadow-lg" buttonColor="tw-bg-transparent"
            buttonLabel="Home" buttonWidth="tw-w-full" cardDisplay="tw-inline-block" dataLoading=""
            itemBgColor="tw-bg-transparent" itemDisplay="tw-block" buttonShadow="tw-shadow-sm" itemFontSize="tw-text-xl"
            buttonDisplay="tw-inline-flex" buttonJustify="tw-justify-center" dataModelType=""
            itemTextColor="tw-text-slate-50" ncTooltipText="" buttonFontSize="tw-text-2xl"
            itemFontWeight="tw-font-normal"
            v-bind:nucalDataModel="{'type':'NSW','isList':true,'update':{'dataModel':'dataModel'},'dynamic':true,'dataModel':'','structure':[{'type':'','update':{'type':'dataModelType','dataModel':'dataModel'},'propName':'options','dataModel':'','displayName':'Value'}]}"
            buttonIconWidth="tw-w-8" buttonTextColor="tw-text-slate-50" itemShadowColor="tw-shadow-transparent"
            buttonFontWeight="tw-font-normal" buttonHoverColor="tw-bg-gray-50" buttonIconHeight="tw-h-12"
            allTextItemsAlign="tw-text-left" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonShadowColor="tw-shadow-transparent" buttonBorderRadius="tw-rounded-md"
            id="5b397689-557a-4956-8382-e4738a85f56a"
            v-bind:style="{'width':'92.25px','height':'35.25px','zIndex':7,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="33.62068965517241%" left="35.1931330472103%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="About Us"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-xl"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="4aae94ee-3432-4122-9525-35689c463ffe"
            v-bind:style="{'width':'121.5px','height':'35.25px','zIndex':8,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="33.05084745762712%" left="42.642857142857146%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Services"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-xl"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="51cf3cd8-8621-4214-a701-cf550f0ed97a"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':9,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="32.20338983050848%" left="50.285714285714285%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Portfolio"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-xl"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="cda13e8a-1bdb-4a53-9d2a-7647f062228e"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':10,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="32.20338983050848%" left="58.785714285714285%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="References"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-xl"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="22705a62-9dd0-474f-913f-dab55170e40c"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':11,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="33.898305084745765%" left="68.28571428571429%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Latest News"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-xl"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="c5856317-edab-4c3d-a345-86003de39ada"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':12,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <WButton tag="button" top="22.88135593220339%" left="83.64285714285714%" v-bind:pill="false" size="md"
            text="Contact us" type="button" v-bind:block="false" color="" v-bind:snapX="false" v-bind:snapY="false"
            theme="theme--light01" v-bind:squared="false" variant="primary" ncBgType="bgColor" position="absolute"
            v-bind:isEnabled="true" background="#1a6ec6" borderColor="#007bff" ncTypography="custom"
            v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="60px" horizontalWidth="72.4479px" nucalScaleWidth=""
            horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF" ncFocusFontColor="#FFFFFF"
            ncHoverFontColor="#FFFFFF" nucalScaleHeight="" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" ncDisableBorderColor="transparent"
            ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4"
            ncDisableBackgroundColor="#969696" id="3c7cdb80-8b13-4706-878c-91119ec67cfd"
            v-bind:style="{'width':'123.75px','height':'48.75px','zIndex':13,'fontSize':'15.75px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'1.0499999999999998','marginLeft':'','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','paddingBottom':'','borderTopWidth':'0.75px','textDecoration':'none','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','horizontalHeight':'28.151025px','borderBottomWidth':'0.75px','borderTopLeftRadius':'3px','borderTopRightRadius':'3px','borderBottomLeftRadius':'3px','borderBottomRightRadius':'3px'}"/>
        </NucGroupElement>
        <WInput id="8fb0f876-096e-4342-be3c-b34511ecad6b" top="0.8261445068236798%" v-bind:lazy="false"
          left="10.255470805715618%" size="md" step="" text="info@ulmer-agentur.de" v-bind:trim="false"
          v-bind:snapX="false" v-bind:snapY="false" v-bind:noWheel="false" v-bind:disabled="false" position="absolute"
          v-bind:readonly="false" v-bind:required="false" wordList="" v-bind:autofocus="false" v-bind:plaintext="true"
          background="" ariaInvalid="false" v-bind:debounceVal="0" ncInputType="text" placeholder="Enter something..."
          v-bind:previewMode="true" autocomplete="" ncTypography="custom" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:isWordListOpen="false"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','ncKey':'type','ncType':{'ncInputType':'number'},'ncValue':'number','propName':'text','displayName':'Value','nsDefaultValue':'string'}]}"
          v-bind:isNumberConvert="false" ncClickFontColor="#434855" ncFocusFontColor="#434855"
          ncHoverFontColor="#434855" ncMaxNumberValue="100" ncMinNumberValue="0" ncClickBorderColor="#000000"
          ncDisableFontColor="#434855" ncFocusBorderColor="#000000" ncHoverBorderColor="#000000"
          ncDisableBorderColor="#000000" formatterFunctionName="" ncClickBackgroundColor="#ffffff"
          ncFocusBackgroundColor="#ffffff" ncHoverBackgroundColor="#ffffff" ncDisableBackgroundColor="#ffffff"
          v-bind:style="{'color':'','width':'','height':'','zIndex':11,'fontSize':'13.5px','maxWidth':'','minWidth':'118.5px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'0.75','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'underline'}"/>
        <WIconButton tag="button" top="1.0498687664041995%" icon="fas fa-envelope" left="7.301360057265569%"
          v-bind:pill="false" size="sm" text="BUT" type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="4px" position="absolute" fontStyle="normal" iconColor="#022b56" v-bind:isEnabled="true"
          minHeight="2px" background="#ffffff" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="20px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#FFFFFF" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#FFFFFF" ncDisableBackgroundColor="#4285f4"
          id="34005820-38a9-44e5-948f-e1128311d552"
          v-bind:style="{'width':'31.5px','height':'17.25px','zIndex':13,'maxWidth':'','minWidth':'1.5px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.75px','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'3px','borderTopRightRadius':'3px','borderBottomLeftRadius':'3px','borderBottomRightRadius':'3px'}"/>
        <WIconButton tag="button" top="0.6561679790026247%" icon="fas fa-phone-square-alt" left="36.22047244094488%"
          v-bind:pill="false" size="sm" text="BUT" type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="4px" position="absolute" fontStyle="normal" iconColor="#022b56" v-bind:isEnabled="true"
          minHeight="2px" background="#ffffff" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="20px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="dac00062-a056-4d68-a4fb-2f1fb59d7100"
          v-bind:style="{'width':'25.5px','height':'22.5px','zIndex':14,'maxWidth':'','minWidth':'1.5px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.75px','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'3px','borderTopRightRadius':'3px','borderBottomLeftRadius':'3px','borderBottomRightRadius':'3px'}"/>
        <WInput id="e198ed8f-a0f2-456b-b1cc-aa11ab070028" top="0.5420499342969777%" v-bind:lazy="false"
          left="38.80171184022824%" size="md" step="" text="+49 123 456 7890" v-bind:trim="false" v-bind:snapX="false"
          v-bind:snapY="false" v-bind:noWheel="false" v-bind:disabled="false" position="absolute"
          v-bind:readonly="false" v-bind:required="false" wordList="" v-bind:autofocus="false" v-bind:plaintext="true"
          background="" ariaInvalid="false" v-bind:debounceVal="0" ncInputType="text" placeholder="Enter something..."
          v-bind:previewMode="true" autocomplete="" ncTypography="custom" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:isWordListOpen="false"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','ncKey':'type','ncType':{'ncInputType':'number'},'ncValue':'number','propName':'text','displayName':'Value','nsDefaultValue':'string'}]}"
          v-bind:isNumberConvert="false" ncClickFontColor="#434855" ncFocusFontColor="#434855"
          ncHoverFontColor="#434855" ncMaxNumberValue="100" ncMinNumberValue="0" ncClickBorderColor="#000000"
          ncDisableFontColor="#434855" ncFocusBorderColor="#000000" ncHoverBorderColor="#000000"
          ncDisableBorderColor="#000000" formatterFunctionName="" ncClickBackgroundColor="#ffffff"
          ncFocusBackgroundColor="#ffffff" ncHoverBackgroundColor="#ffffff" ncDisableBackgroundColor="#ffffff"
          v-bind:style="{'color':'#000000','width':'174.75px','height':'23.25px','zIndex':15,'fontSize':'13.5px','maxWidth':'','minWidth':'118.5px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'0.75','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'underline'}"/>
        <WImage top="19.736842105263158%" left="0%" v-bind:blank="false" v-bind:snapX="false" v-bind:snapY="false"
          v-bind:rounded="false" stretch="none"
          imageUrl="https://simplar.atakansaracoglu.com/wp-content/uploads/2021/11/AdobeStock_339771292-scaled.jpeg"
          position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
          v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
          ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
          id="363adf7f-21c3-4c62-8f4c-51e952939592"
          v-bind:style="{'width':'1046.25px','height':'456px','zIndex':16,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
        <WTextarea top="38.1578947368421%" v-bind:lazy="false" left="7.885304659498208%" rows="2" size="md"
          text="CREATED FOR SUCCESS" v-bind:trim="false" wrap="soft" v-bind:snapX="false" v-bind:snapY="false" value=""
          v-bind:number="false" maxRows="" v-bind:disabled="false" v-bind:noResize="true" position="absolute"
          v-bind:readOnly="false" v-bind:required="false" v-bind:autoFocus="false" dataModel="string"
          v-bind:plaintext="true" textareaId="textarea" v-bind:ariaInvalid="false" placeholder="Enter something..."
          ncTypography="custom" v-bind:noAutoShrink="false" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModel'},'propName':'text','displayName':'Value'}]}"
          v-bind:stateMinNumber="0" formatterFunctionName="" id="269b2d18-ed25-44a4-86b4-edf69cb1248d"
          v-bind:style="{'color':'#FFFFFF','width':'603px','height':'78.75px','zIndex':17,'fontSize':'45px','maxWidth':'','minWidth':'','fontStyle':'NaN','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','background':'','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0.75px','textDecoration':'none'}"/>
        <WTextarea top="28.94736842105263%" v-bind:lazy="false" left="8.100358422939069%" rows="2" size="md"
          text="BUSINESS THEME" v-bind:trim="false" wrap="soft" v-bind:snapX="false" v-bind:snapY="false" value=""
          v-bind:number="false" maxRows="" v-bind:disabled="false" v-bind:noResize="true" position="absolute"
          v-bind:readOnly="false" v-bind:required="false" v-bind:autoFocus="false" dataModel="string"
          v-bind:plaintext="true" textareaId="textarea" v-bind:ariaInvalid="false" placeholder="Enter something..."
          ncTypography="custom" v-bind:noAutoShrink="false" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModel'},'propName':'text','displayName':'Value'}]}"
          v-bind:stateMinNumber="0" formatterFunctionName="" id="0d566b87-6c2a-407b-a43d-c21917cd2155"
          v-bind:style="{'color':'#FFFFFF','width':'702.75px','height':'63px','zIndex':18,'fontSize':'49.5px','maxWidth':'','minWidth':'','fontStyle':'NaN','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','background':'','fontFamily':'OpenSans-Bold,Open Sans','fontWeight':'normal','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0.75px','textDecoration':'none'}"/>
        <WTextarea top="52.887139107611546%" v-bind:lazy="false" left="8.2319255547602%" rows="2" size="md"
          text="Simplar comes with the huge power of Elementor, which offers great capabilities to edit and style options."
          v-bind:trim="false" wrap="soft" v-bind:snapX="false" v-bind:snapY="false" value="" v-bind:number="false"
          maxRows="" v-bind:disabled="false" v-bind:noResize="true" position="absolute" v-bind:readOnly="false"
          v-bind:required="false" v-bind:autoFocus="false" dataModel="string" v-bind:plaintext="true"
          textareaId="textarea" v-bind:ariaInvalid="false" placeholder="Enter something..." ncTypography="custom"
          v-bind:noAutoShrink="false" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModel'},'propName':'text','displayName':'Value'}]}"
          v-bind:stateMinNumber="0" formatterFunctionName="" id="29b52a1c-8c30-4713-8f1a-5b6504803c19"
          v-bind:style="{'color':'#FFFFFF','width':'556.5px','height':'65.25px','zIndex':19,'fontSize':'18.75px','maxWidth':'','minWidth':'','fontStyle':'NaN','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','background':'','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0.75px','textDecoration':'none'}"/>
        <WImage top="66.7979002624672%" left="17.823908375089477%" v-bind:blank="false" v-bind:snapX="false"
          v-bind:snapY="false" v-bind:rounded="false" stretch="none"
          imageUrl="https://www.linkpicture.com/q/360_F_215702641_LBZwxehoMXyY44EPY20vz2mce6bcpeM0_prev_ui.png"
          position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
          v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
          ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
          id="63cdfa5e-db67-40a5-adcc-083a6779ffee"
          v-bind:style="{'width':'96px','height':'67.5px','zIndex':20,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
        <TwPrimaryButton top="69.55380577427822%" left="10.164638511095204%" v-bind:snapX="false" v-bind:snapY="false"
          position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Buy Now"
          buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-2xl"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
          buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-medium"
          buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
          buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
          buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
          id="2453532e-401e-4985-8d1e-33290c47440f"
          v-bind:style="{'width':'108.75px','height':'35.25px','zIndex':21,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
      </NucGroupElement>
    </NucGridCell>
  </NucGridPage>
</template>
<script>
export default {
  name: 'Screen1',
  data() {
    return {};
  },
  props: {},
  created() {},
  mounted() {},
  computed: {},
  methods: {},
  watch: {},
};
</script>

<style scoped></style>